jobs:
  - name: use_state
    type: runSh
    steps:
      - IN: my_state
      - IN: test_state_repo
        switch: off
      - TASK:
        - script: "ls -latr /build/IN/my_state/state/"
        - script: "if [ -f /build/IN/my_state/state/now2.state ]; then echo IN state: $(cat /build/IN/my_state/state/now2.state); fi"
        - script: echo NOW=$(date) > /build/OUT/my_state/state/now2.state
        - script: "echo OUT state: $(cat /build/OUT/my_state/state/now2.state)"
      - OUT: my_state
