jobs:
  - name: use_state
    type: runSh
    steps:
      - IN: my_state
      - IN: test_state_repo
        switch: off
      - TASK:
        - script: echo "IN state: " $(cat /build/IN/my_state/state/now.state)
        - script: echo NOW=$(date) > /build/OUT/my_state/state/now.state
        - script: echo "OUT state: " $(cat /build/OUT/my_state/state/now.state)
      - OUT: my_state
