jobs:
  - name: create_state
    type: runSh
    steps:
      - IN: test_state_repo
        switch: off
      - TASK:
        - script: ls -ltra /build/OUT/test_env_ecs
        - script: cat /build/OUT/test_env_ecs/version.json
        - script: echo versionName=$(date) > $JOB_STATE/test_env_ecs.env
        - script: echo action=CREATE >> $JOB_STATE/test_env_ecs.env
        - script: echo foo=BAR >> $JOB_STATE/test_env_ecs.env
        - script: cat $JOB_STATE/test_env_ecs.env
      - OUT: test_env_ecs
        extend: false
      
  - name: clear_state
    type: runSh
    steps:
      - TASK:
        - script: echo versionName=$(date) > $JOB_STATE/test_env_ecs.env
        - script: echo action=CLEAR >> $JOB_STATE/test_env_ecs.env
        - script: cat $JOB_STATE/test_env_ecs.env
      - OUT: test_env_ecs
