jobs:
  - name: create_state
    type: runSh
    steps:
      - IN: my_state
      - TASK:
        - script: "ls -latr /build/IN/my_state/state/"
        - script: echo versionName=$(date) > /build/OUT/my_state/state/my_state.env
        - script: echo action=CREATE > /build/OUT/my_state/state/my_state.env
        - script: echo foo=BAR > /build/OUT/my_state/state/my_state.env
        - script: cat /build/OUT/my_state/state/my_state.env
      - OUT: my_state
      
  - name: clear_state
    type: runSh
    steps:
      - IN: my_state
      - TASK:
        - script: "ls -latr /build/IN/my_state/state/"
        - script: echo versionName=$(date) > /build/OUT/my_state/state/my_state.env
        - script: echo action=CLEAR > /build/OUT/my_state/state/my_state.env  
      - OUT: my_state
